config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    //$routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Users', 'action' => 'register']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Comment.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Comment Entity
 *
 * @property int $id
 * @property string $comment
 * @property int $user_id
 * @property int $post_id
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime|null $modified
 * @property \Cake\I18n\FrozenTime|null $deleted_date
 * @property bool $deleted
 *
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\Post $post
 */
class Comment extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'comment' => true,
        'user_id' => true,
        'post_id' => true,
        'created' => true,
        'modified' => true,
        'deleted_date' => true,
        'deleted' => true,
        'user' => true,
        'post' => true,
    ];
}

src/Model/Table/CommentsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Comments Model
 *
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\PostsTable&\Cake\ORM\Association\BelongsTo $Posts
 *
 * @method \App\Model\Entity\Comment get($primaryKey, $options = [])
 * @method \App\Model\Entity\Comment newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Comment[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Comment|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Comment saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Comment patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Comment[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Comment findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 * @mixin \Cake\ORM\Behavior\CounterCacheBehavior
 */
class CommentsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('comments');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
        $this->addBehavior('CounterCache', [
            'Posts' => [
                'comment_count' => [
                    'conditions' => ['Comments.deleted' => false]
                ]
            ],
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Posts', [
            'foreignKey' => 'post_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('comment')
            ->maxLength('comment', 140, 'Comment should not be more than 140 Characters')
            ->requirePresence('comment', 'create')
            ->notEmptyString('comment', 'Ops. You forgot to say something.')
            ->add('comment', 'custom',  [
                'rule' => function ($value, $context) {
                    if (strlen(trim($value)) == 0) {
                        return false;
                    }
                    return true;
                },
                'message' => 'Ops. You forgot to say something'
            ]);

        $validator
            ->dateTime('deleted_date')
            ->allowEmptyDateTime('deleted_date');

        $validator
            ->boolean('deleted')
            ->notEmptyString('deleted');

        return $validator;
    }

    /**
     * Getting Comments for Pagination 
     * 
     * @param array $containOptions, array $conditions, int $page, int $limit
     * @return array $comments
     */
    public function fetchComments($containOptions, $conditions, $page, $limit)
    {
        $query = $this->find('all')
            ->contain($containOptions)
            ->order(['Comments.created' => 'ASC'])
            ->where($conditions)
            ->page($page, $limit)
            ->limit($limit);
        $comments = $query->all();

        return $comments;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['post_id'], 'Posts'));

        return $rules;
    }
}

src/Model/Table/PostsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Josegonzalez\Upload\Validation\DefaultValidation;
use Cake\Database\Expression\QueryExpression;
use Cake\ORM\Query;

/**
 * Posts Model
 *
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\RetweetedPostsTable&\Cake\ORM\Association\BelongsTo $RetweetedPosts
 * @property \App\Model\Table\CommentsTable&\Cake\ORM\Association\HasMany $Comments
 * @property \App\Model\Table\LikesTable&\Cake\ORM\Association\HasMany $Likes
 *
 * @method \App\Model\Entity\Post get($primaryKey, $options = [])
 * @method \App\Model\Entity\Post newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Post[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Post|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Post saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Post patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Post[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Post findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PostsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('posts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        //Add Upload Behavior
        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'post_image' => [
                'fields' => [
                    'dir' => 'post_image_dir',
                    'size' => 'post_image_size',
                    'type' => 'post_image_type',
                ],
                'path' => 'webroot{DS}img{DS}post{DS}',

                'nameCallback' => function (array $data, array $settings) {
                    $ext = pathinfo($data['name'], PATHINFO_EXTENSION);
                    return md5(uniqid(rand(), true)) . '.' . $ext;
                },
                'keepFilesOnDelete' => false,
            ],
        ]);

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
        ]);

        $this->belongsTo('RetweetedPost', [
            'className' => 'Posts',
            'foreignKey' => 'retweeted_post_id'
        ]);

        $this->hasMany('Comments', [
            'foreignKey' => 'post_id',
        ])
            ->setConditions(['Comments.deleted' => false]);

        $this->hasMany('Likes', [
            'foreignKey' => 'post_id',
        ]);

        //To get the latest comment in the post
        $this->hasOne('RecentComments', [
            'className' => 'Comments',
            'foreignKey' => false,
            'conditions' => function (QueryExpression $exp, Query $query) {
                $subquery = $query
                    ->connection()
                    ->newQuery()
                    ->select(['Comments.id'])
                    ->from(['Comments' => 'comments'])
                    ->where(['Posts.id = Comments.post_id AND Comments.deleted = false'])
                    ->order(['Comments.created' => 'DESC'])
                    ->limit(1);

                return $exp->add(['RecentComments.id' => $subquery]);
            }

        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('post')
            ->maxLength('post', 140, 'Post should not be more than 140 Characters')
            ->requirePresence('post', 'create')
            ->notEmptyString('post', 'Ops. You forgot to say something.')
            ->add('post', 'custom',  [
                'rule' => function ($value, $context) {
                    if (strlen(trim($value)) == 0) {
                        return false;
                    }
                    return true;
                },
                'message' => 'Ops. You forgot to say something'
            ]);

        $validator->allowEmptyFile('post_image');

        $validator->setProvider('upload', DefaultValidation::class);

        $validator->add('post_image', 'validFileFormat', [
            'rule' => function ($value, $context) {
                $allowedFiles = ['png', 'jpg', 'jpeg', 'PNG', 'JPG', 'JPEG'];
                $extension = pathinfo($context['data']['post_image']['name'], PATHINFO_EXTENSION);
                return in_array($extension, $allowedFiles);
            },
            'message' => 'Invalid File format. Only .png, .jpg, .jpeg are allowed',
            'provider' => 'upload',
        ]);

        $validator->add('post_image', 'fileBelowMaxSize', [
            'rule' => ['isBelowMaxSize', 2000000],
            'message' => 'This file is too large, 2MB is the max size of the file',
            'provider' => 'upload'
        ]);

        $validator->add('post_image', 'fileCompletedUpload', [
            'rule' => 'isCompletedUpload',
            'message' => 'This file could not be uploaded completely',
            'provider' => 'upload'
        ]);

        $validator->add('post_image', 'UPLOAD_ERR_INI_SIZE', [
            'rule' => function ($value, $context) {
                if ((int) $context['data']['post_image']['error'] === 1) {
                    return false;
                };
                return true;
            },
            'message' => 'This file exceeds the upload max file size'
        ]);


        $validator
            ->dateTime('deleted_date')
            ->allowEmptyDateTime('deleted_date');

        $validator
            ->boolean('deleted')
            ->notEmptyString('deleted');

        $validator
            ->integer('comment_count')
            ->notEmptyString('comment_count');

        $validator
            ->integer('like_count')
            ->notEmptyString('like_count');
        return $validator;
    }

    /**
     * Getting Posts for Pagination 
     * 
     * @param array $containOptions, array $conditions, int $page, int $limit
     * @return array $posts
     */
    public function fetchPosts($containOptions, $conditions, $page, $limit)
    {
        $postQuery = $this->find('all')
            ->contain($containOptions)
            ->order(['Posts.created' => 'DESC'])
            ->where($conditions)
            ->page($page, $limit)
            ->limit($limit);
        $posts = $postQuery->all();

        return $posts;
    }

    /**
     * Get And Validate Post method 
     *   
     * @param string|null $id Post id, int|null $userId, array $containOption.
     * @return \Cake\Http\Response 
     * @throws \Cake\Http\Exception\ForbiddenException | \Cake\Http\Exception\NotFoundException
     */
    public function getAndValidatePost($id = null, $userId = null, $containOption = [])
    {
        if (!$id) {
            throw new \Cake\Http\Exception\NotFoundException('No Post Reference');
        }

        $postQuery = $this->find('all')
            ->contain($containOption)
            ->where(['Posts.id' => (int) $id, 'Posts.deleted' => false]);

        $post = $postQuery->first();

        if (!$post) {
            throw new \Cake\Http\Exception\NotFoundException('Post does not exist');
        }

        if ($userId != null) {
            if ($post->user_id != $userId) {
                throw new \Cake\Http\Exception\ForbiddenException('Request not authorized');
            }
        }

        return $post;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['retweeted_post_id'], 'RetweetedPost'));

        return $rules;
    }
}

src/Template/Comments/edit.ctp
<?php
if (!isset($error)) {
?>
    <?= $this->Form->create($comment, [
        'type' => 'file',
        'url' => ['controller' => 'Comments', 'action' => 'editPost'],
        'class' => 'edit-comment-form'
    ])
    ?>
    <?= $this->Form->control('comment', [
        'label' => false,
        'id' => 'input-post',
        'class' => 'form-control form__inputs',
        'type' => 'textarea',
        'required' => false,
        'templates' => [
            'inputContainer' => '{{content}}'
        ],
    ])
    ?>
    <span class="form__input-error text-danger"></span>

    <div class="float-right">
        <div class="input-group" id="button_post_div">
            <input type="text" id="input-post-count" disabled size="4" />
            &nbsp;
            <?= $this->Form->button(
                _('Save Comment'),
                [
                    'class' => 'btn-sm btn-success',
                ]
            )
            ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
<?php } ?>

src/Template/Comments/fetch_comment.ctp
<div class="comment-content" id="page<?= h($page) ?>" style="display:block;">
    <?php foreach ($comments as $comment) { ?>
        <div class="post-comments">
            <?php if ($me['id'] == $comment->user_id) { ?>
                <div class="float-right">
                    <div class="dropleft">
                        <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                            ...
                        </a>
                        <div class="dropdown-menu">
                            <?php
                            echo $this->Html->link(
                                'Edit',
                                ['controller' => 'Comments', 'action' => 'edit', h($comment->id)],
                                ['class' => 'edit_comment_link dropdown-item']
                            );
                            echo $this->Form->postLink(
                                'Delete',
                                ['controller' => 'Comments', 'action' => 'delete', h($comment->id)],
                                [
                                    'confirm' => 'Are you sure to delete?',
                                    'class' => 'dropdown-item'
                                ]
                            );
                            ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="div_pic_name">
            <?php
            echo '<div class="cropper-profile">'; 
            echo $this->Html->image(
                empty($comment->user->image) ? 'user.jpg' : '/img/user/' . h($comment->user->image),
                [
                    'class' => 'pic'
                ]
            );
            echo '</div>';
            echo '&nbsp;';
            ?>
            <?= $this->Html->link(
                h($comment->user->username),
                ['controller' => 'Users', 'action' => 'userPage', h($comment->user->id)],
            )
            ?>
            </div>
            <p><?= h($comment->comment) ?></p>
        </div>
    <?php } ?>
</div>

src/Template/Comments/see_more.ctp
<div class='row'>
    <div class='col-md-5 col-lg-5'>
        <!--start-->
        <div class='div_post card'>
            <!--start-->
            <div class='div-post-upper'>
                <div class='div_pic_name'>
                    <div class='cropper-profile'>
                    <?php echo $this->Html->image(
                        empty($post->user->image) ? 'user.jpg' : '/img/user/' . h($post->user->image),
                        [
                            'class' => 'pic'
                        ]
                    );
                    ?>
                    </div>
                    &nbsp;
                    <h6>
                        <?= $this->Html->link(
                            h($post->user->username),
                            ['controller' => 'Users', 'action' => 'userPage', h($post->user->id)],
                        )
                        ?>
                    </h6>
                </div>
                <p><?= h($post->post) ?></p>
                <?php
                if ($post->post_image != null) {
                    echo '<div class="card bg-secondary">';
                    echo $this->Html->image(
                        '/img/post/' . h($post->post_image),
                        [
                            'class' => 'center post_img',
                            'alt' => h($post->post)
                        ]
                    );
                    echo '</div>';
                }
                ?>
                <?php if ($post->retweeted_post_id != null) { ?>
                    <a href="<?= $this->request->getAttribute('webroot') . 'posts/view/' . h($post->retweeted_post_id) ?>" class='post-view-link'>
                        <div class='div_post card'>
                            <?php if ($post->retweeted_post->deleted) {
                                echo '<p class="text-danger">The post has been removed.</p>';
                            } else {
                                echo '<div class="div_pic_name">';
                                echo '<div class="cropper-profile">';
                                echo $this->Html->image(
                                    empty($post->retweeted_post->user->image)
                                        ? 'user.jpg'
                                        : '/img/user/' . h($post->retweeted_post->user->image),
                                    [
                                        'class' => 'pic'
                                    ]
                                );
                                echo '</div>';
                                echo '&nbsp;';
                                echo '<h6>' . h($post->retweeted_post->user->username) . '</h6>';
                                echo '</div>';
                                echo '<p>' . h($post->retweeted_post->post) . '</p>';

                                if ($post->retweeted_post->post_image != null) {
                                    echo '<div class="card bg-secondary">';
                                    echo $this->Html->image(
                                        '/img/post/' . h($post->retweeted_post->post_image),
                                        [
                                            'class' => 'center post_img',
                                            'alt' => h($post->retweeted_post->post)
                                        ]
                                    );
                                    echo '</div>';
                                }
                            } ?>
                        </div>
                    </a>
                <?php } ?>
            </div>
            <div class='row'>
                <div class='col-md-12 col-lg-12 col-sm-12'>
                    <div class='float-left'>
                        <a href='#' class='number-of-likes' data-post='<?= h($post->id) ?>'>
                            <small id='postcount<?= h($post->id) ?>'>
                                <?php
                                if ($post->like_count > 0) {
                                    echo $post->like_count > 1 ?
                                        h($post->like_count) . ' Likes' :
                                        h($post->like_count) . ' Like';
                                }
                                ?>
                            </small>
                        </a>
                    </div>
                    <div class='float-right'>
                        <small>
                            <?php
                            if ($post->comment_count > 0) {
                                echo $this->Html->link(
                                    $post->comment_count > 1 ?
                                        $post->comment_count . ' Comments' :
                                        $post->comment_count . ' Comment',
                                    ['controller' => 'Comments', 'action' => 'seeMore', h($post->id)],
                                );
                            }
                            if ($post->retweet_count > 0) {
                                echo '&nbsp';
                                echo '<span class="text-primary">';
                                echo $post->retweet_count > 1 ? h($post->retweet_count) . ' Retweets' :
                                    h($post->retweet_count) . ' Retweet';
                                echo '</span>';
                            }
                            ?>
                        </small>
                    </div>
                </div>
            </div>
            <div class='d-flex justify-content-between'>
                <div class='float-left'>
                    <?php if (empty($post->likes)) {
                        echo '<a href="#" class="like-post" data-post="' . h($post->id) . '">Like</a>';
                    } else {
                        if ($post->likes[0]->deleted) {
                            echo '<a href="#" class="like-post" data-post="' . h($post->id) . '">Like</a>';
                        } else {
                            echo '<a href="#" class="like-post" data-post="' . h($post->id) . '">Unlike</a>';
                        }
                    } ?>
                </div>
                <div class='float-right'>
                    <div class='dropdown'>
                        <button class='dropbtn'>...</button>
                        <div class='dropdown-content'>
                            <?php
                            if ($me['id'] == $post->user_id) {
                                echo $this->Html->link(
                                    'Edit',
                                    ['controller' => 'posts', 'action' => 'edit', h($post->id)],
                                    ['class' => 'edit_post_link']
                                );
                                echo $this->Form->postLink(
                                    'Delete',
                                    ['controller' => 'posts', 'action' => 'delete', h($post->id)],
                                    [
                                        'confirm' => 'Are you sure to delete?',
                                    ]
                                );
                            }
                            echo $this->Html->link(
                                'Retweet',
                                ['controller' => 'posts', 'action' => 'retweet', h($post->id)],
                                ['class' => 'retweet_post_link']
                            );
                            echo $this->Html->link(
                                'View',
                                ['controller' => 'posts', 'action' => 'view', h($post->id)],
                            );
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end-->
    </div>
    <div class='col-md-7 col-lg-7'>
        <div class='div_post'>
            <div id='load_data'></div>
            <div id='load_data_message'></div>
            <div class='div_comment_form'>
                <div class='cropper-comment-form'>
                    <?php echo $this->Html->image(
                        empty($me['image']) ? 'user.jpg' : '/img/user/' . h($me['image']),
                        [
                            'alt' => 'You',
                            'class' => 'pic'
                        ]
                    );
                    ?>
                </div>
                <div>
                    &nbsp;
                    <?php
                    echo $this->Html->link(
                        h($me['username']),
                        ['controller' => 'Users', 'action' => 'userPage', h($me['id'])],
                    );
                    echo $this->Form->create($newComment, [
                        'url' => ['controller' => 'Comments', 'action' => 'add'],
                        'class' => 'save-comment comment-form',
                        'type' => 'post'
                    ]);
                    echo '&nbsp;';
                    echo $this->Form->control(
                        'comment',
                        [
                            'class' => 'form-control',
                            'type' => 'text',
                            'style' => 'width:450px',
                            'label' => false,
                            'required' => false,
                        ]
                    );
                    echo $this->Form->control(
                        'post_id',
                        [
                            'type' => 'hidden',
                            'value' => h($post->id),
                            'id' => 'post_id'
                        ]
                    );
                    echo '&nbsp;';
                    echo $this->Form->button(__('Comment'), [
                        'class' => 'btn-sm btn-success',
                    ]);

                    echo $this->Form->end();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    init(false);

    var url = getCommentUrl();
    var data = function(limit, page) {
        return {
            post_id: getPost(),
            limit: limit,
            page: page,
        }
    }
</script>